### PR TITLE
feat: add template, description and androidx support

### PR DESCRIPTION
**Pull request by devhammed**
I have added support for template type, description and AndroidX.

Description:
Screenshot from 2020-06-18 06-41-52

Project Template:
Screenshot from 2020-06-18 06-41-44

Use AndroidX?
Screenshot from 2020-06-18 06-41-56

Generated Command:
Screenshot from 2020-06-18 06-56-28

### CODE REVIEW

**Comment by prasadsunny1** [comment]
@piedcipher,@devhammed Do we need a way to ask the user for android-x support?
I believe it has to be enforced by default, All projects should be android-x based by default.

**Comment by devhammed** [comment]
> @piedcipher,@devhammed Do we need a way to ask the user for android-x support?
> I believe it has to be enforced by default, All projects should be android-x based by default.
> 

@prasadsunny1 , This PR is pretty old 😂😂😂

**Comment by prasadsunny1** [comment]
So, Do you want to close it instead?

**Comment by devhammed** [comment]
@prasadsunny1 No, I can remove that particular prompt.

**Comment by devhammed** [comment]
@prasadsunny1 closed 😂😂😂

**Pull request closed without merging**
